
spring.application.name: zuul-service
server.port: 8070

spring.devtools.restart.enabled: true

#------------日志-------------------
logging:
  config: classpath:logback-spring.xml
  path: /data/deploy/log/${spring.application.name}


#--------------eureka------------------
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      #向三个服务端分别注册
      defaultZone: http://192.168.1.61:20001/eureka/,http://192.168.1.63:20002/eureka/  #eureka服务的位置
    register-with-eureka: true #向eureka注册服务
    fetch-registry: true #拉取注册表的本地副本

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    luozijian-service: /ls/**